# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "BbJS0n4B9+sOT1IU/ejh+FVIrA5caKBAQhT97XELjzfEMHdrdUFEzskqgVgeT9dOWoWNBY+nY3CMx9Jx8+JMvK4vJDBCo12uKNbfRt7/ZUHKTsS/9+kW1D2A2C2pM5cbvEuzz9OvTErl9B5UAuxMPOMyKE5t8alju6cekciS6F7e4jjtblZ+2WT8HwYjzNF5NnSxPnNQLSpYcDO2VRFwG/eCgmN/VRYfBuI/Fwrws1dIHJe/TOW/vQvyMluxONmhCHpCnsDXvtSLxtFm9ZoOj89xsqHio3wRP1pDiX27u6oeeCTPWgQQkqkM6ZwB08wp0oERyI26M+uDCf9kfbGBmkgSdxPH6l3XhL9P+wz/DqkleAqhN1YbhklbRBPcPuwtlDVFwWUgBp8+SfJRbaLjPNczMDhiIpskVgYPaavpm3NS4ihYflr7Cf2V7izr8m9ecbQzFwXg5YtJScWzxMvXu98SxoVUtwyup86sZcjLW1fBvfS2yYWNsDknGF03Rn71hNfnGm9GUQK0YYsH7rWCsOsQCNrdDJ91PxhsuPla7UfFfi9CacmvZkBq/G+OdmaGi8zy9VIMKzK7hiM6EpSqhO6ottUDfzFoOzjCFR2CjoJZe1ppvEfh07UuJqgxajVuOaNONYqj4Gtn2FInjhFvvBOvvw4EeTPNXSyy+Q4hfLU="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-ci-setup=1
      source run_conda_forge_build_setup

script:
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml

  - upload_or_check_non_existence ./recipe conda-forge --channel=main -m ./.ci_support/${CONFIG}.yaml
