appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: wHxPUqEun3jIoYYYRTcRzMuqa57ZnevD20hHloZ58nQezJnThuFXCbsVUKBV9Uv4C6zKmrUt6j9EzNMyCNdR0akYuoZhbUkXvDYyQ1B+W9XderGBHGi8bZHCuILv+xLOb7z7en7BdU5awdB+ZfOKnsNRybkjw/SaZ/Cy9R+0RK6sbKr3Om1uxtokKxRsx2d7rZVWHVQy5kP+Ox7DfWu5GiKDkvtpbUtMhRctSXacrHsccmCgiDIzQ2RaP535rrtP6K2o+UVP+dG4u3m43ggqeN3PZ5kIIaMhOOCrwe9FbYhPRXVhyxbx7QWugNddGRdloSbCGvGS/gA07deT3e6fAwz8ewIV2gRLobA6tiBQ8nZJnM2ayu+Q9HnhdT8pJZ0/Y+OCk6VhpoLfbof8kq+PFqIxcgyUINqMEAVdtgprBHUMMtiSBecn1HNa52VAa4Aff68sGBzOYsgxXDiDgYU/i27TLZZ0FN2YeFQf+ts12COuQOt7svFYDS9BfxtDke33cOg0gRRpnDWAWJM5FLA4EMsiFkyc7waKFOGqM9V7R816MvIaSHxUhg5lOypeWYrQXX2xh2Qnhs7oe+tZrdtSCkA2nRD1fkPFnpDSRm+MyEO9/3M5YoyhhfqpjOIRV6/Xv0XvldeHfRnC2998RAmuEITQkLIbzejJ2MLEg2KtT4c=}
